# Production override for docker-compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: "3.8"

services:
  qdrant:
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 1G
          cpus: "0.5"

  ollama:
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
        reservations:
          memory: 2G
          cpus: "1.0"

  tika:
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"

  cms-app:
    restart: always
    environment:
      - JAVA_OPTS=-Xmx3g -Xms1g -XX:+UseG1GC -XX:+UseStringDeduplication
      - DOCKER_ENV=true
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
        reservations:
          memory: 1G
          cpus: "1.0"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
