version: '3.8'
services:
  ollama:
    image: tonioacr123.azurecr.io/ollama:latest
    container_name: ollama
    command: ["serve"]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    shm_size: '1g'
    restart: unless-stopped

volumes:
  ollama_data:
