name: Java CI with Maven

permissions:
  contents: write   # nötig, damit die Snapshot-Action in den Dependency Graph schreiben darf :contentReference[oaicite:0]{index=0}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '23'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file diplomarbeit/DiplomarbeitCMS/pom.xml

    - name: Generate & Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v5  # aktuelle Version mit Plugin 4.0.3 :contentReference[oaicite:1]{index=1}
      with:
        directory: 'diplomarbeit/DiplomarbeitCMS'  # Pfad zu deinem pom.xml :contentReference[oaicite:2]{index=2}
        token: ${{ secrets.GITHUB_TOKEN }}
