name: Java CI with Maven

permissions:
  contents: write   # nötig, wenn du den Dependency-Graph nutzen willst

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '23'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file diplomarbeit/DiplomarbeitCMS/pom.xml

    # Wenn du den GitHub Dependency Graph nicht aktivierst, kommentiere diesen Schritt aus:
    # - name: Generate & Submit Dependency Snapshot
    #   uses: advanced-security/maven-dependency-submission-action@v5
    #   with:
    #     directory: 'diplomarbeit/DiplomarbeitCMS'
    #     token: ${{ secrets.GITHUB_TOKEN }}
