name: Java CI with Maven

# Erforderliche Rechte, damit die Dependency-Submission-Action in den Dependency-Graph schreiben darf
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '23'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file diplomarbeit/DiplomarbeitCMS/pom.xml

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        directory: 'diplomarbeit/DiplomarbeitCMS'
        token: ${{ secrets.GITHUB_TOKEN }}
